from time import sleep as wait
from input import ask, choice
from sys import exit

money = 0

def start():

    print("you go to the gun shop to get a gun")
    wait(1)
    print("there are three guns on the table")
    wait(1)
    print("1) pistol")
    print("2) minigun")
    print("3) pistol with silencer and scope")
    print("the gun shop owner asks: 'which gun do you want?'")

    answer = ask(allowedAnswers=["1", "2", "3"], falseInputResponce="you must list a number from 1 - 3")

    global gun

    if answer == "1":
        gun = "pistol"
        print("you picked the normal pistol")
    elif answer == "2":
        gun = "minigun"
        print("you picked the minigun, it is powerful but hard to carry around")
    else:
        gun = "large pistol"
        print("you picked the large pistol")

    wait(1)
    print("on another table you there are 4 items")
    wait(1)
    print("You only have enough money for 2 items")
    shopItems = ["a lock picking set", "a taser", "a thermal camera", "quiet stealth shoes"]
    items = []
    answer = choice(shopItems)
    if answer == 1:
        print("you pick the lock picking set")
        shopItems.remove("a lock picking set")
        items.append("lock pick")
    elif answer == 2:
        print("you pick the taser")
        shopItems.remove("a taser")
        items.append("taser")
    elif answer == 3:
        print("you pick the thermal camera")
        shopItems.remove("a thermal camera")
        items.append("thermal camera")
    elif answer == 4:
        print("you pick the stealth shoes")
        shopItems.remove("quiet stealth shoes")
        items.append("stealth shoes")

    print("you have enough money for 1 more item")
    answer = choice(shopItems)
    if shopItems[answer - 1] == "quiet stealth shoes":
        items.append("stealth shoes")
    elif shopItems[answer - 1] == "a thermal camera":
        items.append("thermal camera")
    elif shopItems[answer - 1] == "a taser":
        items.append("taser")
    elif shopItems[answer - 1] == "lock picking set":
        items.append("lock pick")
    print("you also decide to grab a kunai, using the rest of your money")
    wait(2)
    print("1) ask a friend to join you when you rob the bank")
    print("2) rob the bank without a friend")
    answer = ask(allowedAnswers=["1", "2"])
    if answer == "1":
        print("you arrive to your friends house")
        wait(1)
        print("you don't think he is home")
        wait(0.6)
        print("1) ring the door bell")
        print("2) go to the bank")
        answer = ask(allowedAnswers=["1", "2"])

        if answer == "1":
            print("you ring the door bell")
            wait(1.2)
            print("The door opens")
            print("your friend is behind the door")
            print("'hey, so you want to rob that bank with me?' says your friend")
            wait(0.6)
            print("1) yes")
            print("2) no")
            answer = ask(allowedAnswers=["1", "2"])
            global car
            if answer == "1":
                print("'alright, you go the van ready?'")
                wait(0.6)
                answer = choice(["yes", "no"])
                if answer == 1:
                    print("you and your friend are in the van")
                    car = "van"
                else:
                    print("ok, lets take my car then")
                    print("you hop in his lambo")
                    car = "lambo"
                robThebank(True, items)

            else:
                print("ok, bye dude!")
        else:
            print("you go to the bank")
            robThebank(False, items)
    elif answer == "2":
        robThebank(False, items)
    else:
        print("input not understood")

def robThebank(hasAFriend, items):
    if hasAFriend:
        print(f"it is night time you are in the {car}, parked in front of the bank")
        print("'dude, you got your gun ready?'")
        #todo
    else:
        print("it is pitch black, you are parked in front of the bank in your car")
        wait(0.6)
        answer = choice(["rob the bank now before anyone gets suspicious", "wait until 4am when the guards are tired"])
        if answer == 1:
            print(f"you grip your {gun} tightly")
            wait(1.6)
            print("you open your car door slightly and look around for any guards in the area")
            wait(1)
            print("No guards are in sight")
            wait(1)
            print(f"you walk out of the car with your {gun} in your hand")
            wait(1)
            if gun == "minigun":
                print(f"the metal parts of the minigun are making a clunking noise, it may alert the guards")
            else:
                print(f"your {gun} is quiet and light")
            wait(0.7)
            print("eventually you approach a fence")
            wait(0.3)
            answer = choice(["cut the fence", "climb over the fence"])
            if answer == 1:
                print("you take out your fence cutters")
                print("you cut the first wire, the fence makes a loud noise")
                wait(0.2)
                for i in range(4):
                    print("you cut another wire")
                    wait(1.4)
                print("there is now a large hole in the fence")
                wait(4)
                print("you squeeze through the fence..")
                wait(4)
                print("you scream in pain, a sharp part of the fence stabs your back")
                wait(4)
                print("you fall down.")
                wait(4)
                print("you breathe heavily as you try to get back on your feet")
                wait(4)
                print("blood drips down onto the cold, hard dirt")
                wait(4)
                print("you hear some footsteps, a guard must be approaching you")
                wait(4)
                print("you look around you see a guard in the distance with a flashlight")
                wait(4)
                print("he is slowly walking towards the noise")
                wait(4)
                print("in pain, you start crawling away from the guard")
                wait(4)
                print("his footsteps are getting louder and louder")
                wait(4)
                print("with all your might, you manage to get back on your feet, you can barely run")
                wait(4)
                print("with each step you feel a throbbing pain in your back, it feels like someone is stabbing a knife into your back")
                wait(4)
                print("you reach the corner of the building, you sit, leaning against the cold, damp concrete")
                wait(4)
                print("you hear a guard shout 'SOMEONE'S IN THE RED ZONE, THE FENCE HAS BEEN CUT!!'")
                wait(4)
                print("a loud siren turns on")
                wait(4)
                print("you know there is no escape...")
                wait(4)
                print("a guards comes around the corner, he sees you sitting against the concrete, bleeding")
                wait(4)
                print("every thing gets blurry")
                wait(4)
                print("you pass out...")
                exit()
            elif answer == 2:
                print("you grip the wired fence and pull your self up it")
                wait(4)
                print("you get off and land on the other side")
                wait(4)
                print("you check for guards again")
                wait(3)
                print("no guard is in sight")
                print("you continue and reach the corner of the bank")
                wait(4)
                print("you move a little further")
                wait(3)
                print("you reach another corner")
                wait(4)
                print("you lean over to check for guards")
                wait(4)
                print("no one is there")
                wait(3)
                print("you reach the front of the bank")
                wait(3)
                print("the door is locked")
                wait(4)
                answer = choice(["use an explosive too open the door", "shoot at the lock", "find another way to get in"])
                if answer == 1:
                    print("you plant the small explosive on the lock")
                    wait(4)
                    print("you take out a small controller with a red button")
                    wait(4)
                    print("you take a couple steps back and press the button")
                    wait(4)
                    print("the controller makes a couple beeping noises, then...")
                    wait(5)
                    print("BOOM!")
                    print("the door bursts open with tremendous force, the impact of the explosion throws you onto the ground, a dark grey dust fills the air, the flash of the explosion blinds you, your ears are ringing, you feel a bitter taste in your mouth, it is blood, you feel the air sucked out of your lungs, your skin stings from the heat of the explosion")
                    wait(10)
                    print("you start regaining your vision, but your ears are still ringing")
                    print("very faintly you see guards rush towards the door, they pick you up and...")
                    wait(5)
                    exit()
                elif answer == 2:
                    if gun == "large pistol":
                        print("you take the pistol out of your pocket...")
                        wait(4)
                        print("you hold it up to the lock a fire a bullet")
                        wait(4)
                        print("Pshhooo..CLANK!")
                        wait(4)
                        print("The noise alerts the guards.")
                        wait(4)
                        print("you walk into the bank and find the vault")
                    if gun == "pistol":
                        print("you take your pistol")
                        wait(4)
                        print("you shoot the lock")
                        wait(4)
                        print("A piece of shrapnel goes into your head")
                        wait(7)
                        print("YOU DIE")
                        exit()
                    if gun == "minigun":
                        print("you hold the minigun up to the lock, then take a couple steps back")
                        wait(4)
                        print("you gently place your finger over the trigger")
                        wait(4)
                        print("closing one eye you line the gun with the lock")
                        wait(4)
                        print("Then you squeeze the trigger...")
                        wait(4)
                        print("a stream of bullets explode out of the end of the gun, the gun rumbles the earth")
                        wait(5)
                        print("a huge cloud of dust and smoke rises up into the air")
                        wait(4)
                        print("you hear sirens in the distance the police is coming...")
                        wait(4)
                        print("you go through the door and run to the vault")
                    inTheVault()
                elif answer == 3:
                    print("you continue to walk around the bank")
                    wait(4)
                    print("eventually you find the back entrance")
                    wait(4)
                    print("there is a small padlock closing the door")
                    wait(2)
                    answer = choice(["pick the padlock", "break it open"])
                    if answer == 1:
                        if "lock pick" in items:
                            print("you take out your lock picking set")
                            wait(3)
                            print("there are a lot of tools")
                            wait(1)
                            answer = choice(["a flag shaped one", "a saw like one, like a bobby pin", "a flat one"])
                            if answer == 1:
                                print("you take the flag shaped pick out of the small case")
                                wait(4)
                                print("you place it into the keyhole, using another piece metal you apply pressure, you move the pick around a bit")
                                wait(7)
                                print("Cluchik!")
                                wait(2)
                                print("the lock opens")
                            elif answer == 2:
                                print("you take the saw-like pick out of the small case")
                                wait(4)
                                print("you place it into the keyhole, using another piece metal you apply pressure, you move the pick around a bit")
                                wait(7)
                                print("Cluchik!")
                                wait(2)
                                print("the lock opens")
                            elif answer == 3:
                                print("you take out the flat pick out from the small case")
                                wait(4)
                                print("you place it into the keyhole, using another piece metal you apply pressure, you move the pick around a bit")
                                wait(7)
                                print("the lock won't open")
                                wait(6)
                                print("you keep trying but the lock still won't open")
                                wait(5)
                                print("you take another pick out and try again")
                                wait(10)
                                print("Cl-chink!")
                                wait(3)
                                print("the lock opens")
                        else:
                            print("you have no lock picking set")
                            wait(5)
                            print("you sit there, contemplating your life choices")
                            wait(6)
                            print("suddenly a guard walks around the corner")
                            wait(6)
                            print("you lose.")
                            exit()
                    elif answer == 2:
                        wait(3)
                        answer = choice(["use your kunai to open the lock", "use the back of your gun", "use a crowbar"])
                        if answer == 1:
                            print("you stick the kunai through the shackle of the lock")
                            wait(5)
                            print("the lock won't budge")
                            wait(5)
                            print("you keep trying")
                            wait(6)
                            print("suddenly the sharp knife slips and goes into your hand")
                            wait(4)
                            print("you scream in pain")
                            wait(4)
                            print("blood drips from your hand onto the floor")
                            wait(5)
                            print("drop...drop...drop")
                            wait(5)
                            print("you hear guards coming to get you.")
                            wait(10)
                            print("YOU LOSE")
                            exit()
                        elif answer == 2:
                            print("you hit the lock with your gun")
                            wait(4)
                            print("the lock doesn't budge")
                            wait(4)
                            print("you keep trying")
                            wait(10)
                            print("'PUT YOUR HANDS BEHIND YOUR BACK!'")
                            wait(4)
                            print("the guards heard the loud clanks")
                            wait(4)
                            print("YOU LOSE")
                            exit()
                        elif answer == 3:
                            print("you take out a crowbar from your back pack")
                            wait(4)
                            print("you pry open the lock")
                            wait(4)
                            print("the lock pops off")
                print("you go through the door")
                wait(3)
                print("you end up in some sort of maintenance room")
                wait(3)
                print("you might be able to go through a AC vent and go to the vault")
                answer = choice(["go through the AC vent", "find another way into the vault"])
                if answer == 1:
                    print("You open the filter in the AC vent")
                    wait(2)
                    print("You pull yourself inside")
                    wait(2)
                    print("It is cold and damp")
                    wait(2)
                    print("You slowly crawl towards vault")
                    wait(2)
                    print("You reach one vent, you peak down the vent")
                    wait(2)
                    print("You are not in the main hall of the bank")
                    wait(2)
                    print("You see a security guard sleeping in the chair")
                    wait(2)
                    print("You continue down the small tunnel")
                    wait(2)
                    print("you reach another room")
                    wait(2)
                    print("You look down you see the vault door")
                    wait(3)
                    print("You could get off here and try to open the vault door")
                    wait(3)
                    print("You could also try to go straight into the vault room")
                    answer = choice(["Get Down Here", "Go a little further"])
                    if answer == 1:
                        print("You decide to get off here")
                        wait(2)
                        print("You push the filter down and it pops open")
                        wait(2)
                        print("You then slowly get out of the vent")
                        wait(2)
                        print("You are in front of the vault door")
                    elif answer == 2:
                        print("You crawl a little further and find a filter")
                        wait(2)
                        print("You try pushing it but it won't move")
                        wait(2)
                        print("You crawl backwards and reach the first opening")
                        wait(2)
                        print("You push the door open and you come down")
                        wait(2)
                        print("You are now in front of the vault door")
                    inTheVault()
                elif answer == 2:
                    wait(2)
                    print("you find a door, it is unlocked")
                    wait(2)
                    print("you go through the door")
                    wait(3)
                    print("you are in the bank, you look around you see something, or rather someone")
                    wait(4)
                    print("it's a guard")
                    wait(2)
                    answer = choice(["kill the guard", "try to sneak past the guard"])
                    if answer == 1:
                        answer = choice(["use your gun", "use your kunai", "use your taser"])
                        if answer == 1:
                            print(f"your palms are sweaty, your holding your {gun}")
                            wait(2)
                            print("you aim at the guard")
                            if gun == "minigun":
                                print("you aim the minigun at the guard")
                                wait(3)
                                print("you squeeze the trigger")
                                wait(2)
                                print("You killed the guard.")
                                wait(2)
                                print("Then, suddenly the bank doors burst open")
                                wait(2)
                                print("A group of guards storm the bank")
                                wait(3)
                                print("You get arrested")
                                wait(1)
                                print("The End")
                                exit()
                            elif gun == "pistol":
                                print("you aim the pistol at the guard")
                                wait(3)
                                print("you squeeze the trigger")
                                wait(2)
                                print("You killed the guard.")
                                wait(2)
                                print("Then, suddenly the bank doors burst open")
                                wait(2)
                                print("A group of guards storm the bank")
                                wait(3)
                                print("You get arrested")
                                wait(1)
                                print("The End")
                                exit()
                            elif gun == "large pistol":
                                print("you aim the minigun at the guard")
                                wait(3)
                                print("you squeeze the trigger")
                                wait(2)
                                print("Ptchoo")
                                wait(1)
                                print("The guard is dead")
                                print("You see a door that leads to the vault room")
                                wait(2)
                                print("You walk up to the door and open it")
                                wait(2)
                                print("You are in the vault room.")
                                inTheVault()
                        elif answer == 2:
                            if "stealth shoes" in items:
                                print("You start to sneak up to the guard")
                                wait(3)
                                print("your stealth shoes make no noise.")
                                wait(2)
                                print("You are getting closer")
                                wait(2)
                                print("Then, you plunge the kunai into the guards back")
                                wait(2)
                                print("He shrieks")
                                wait(1)
                                print("BANG!")
                                wait(3)
                                print("you feel a warm liquid dripping down your legs")
                                wait(3)
                                print("you look down you see blood pouring out from a hole")
                                wait(4)
                                print("The guard shot you")
                                wait(2)
                                print("you stumble to the ground")
                                wait(2)
                                print("The guard also falls to the ground")
                                wait(1)
                                print("You turn around and face the roof")
                                wait(2)
                                print("Your are breathing heavily")
                                wait(2)
                                print("You know there is no escape")
                                wait(2)
                                print("You slow down your breathing")
                                wait(2)
                                print("Everything starts to get blurry")
                                wait(10)
                                print("YOU LOSE")
                                exit()
                            else:
                                print("You slowly move to the guard, with your kunai tight in your hand")
                                wait(2)
                                print("step by step")
                                wait(2)
                                print("Crunch!")
                                wait(3)
                                print("You alerted the guard.")
                                wait(2)
                                print("the guard swings around, he sees you on the floor")
                                wait(3)
                                print("PUT YOUR HANDS BEHIND YOUR HEAD!")
                                wait(2)
                                print("You do as he asks")
                                wait(2)
                                print("You get arrested")
                                exit()
                        elif answer == 3:
                            if "taser" in items:
                                if "stealth shoes" in items:
                                    print("You slowly walk towards the guard")
                                    wait(2)
                                    print("each step makes no noise.")
                                    wait(2)
                                    print("You are behind the guard")
                                    wait(3)
                                    print("You stab the taser into his neck")
                                    wait(2)
                                    print("ZHzhzhzhz")
                                    wait(2)
                                    print("The guard shouts")
                                    wait(2)
                                    print("He turns around and shoots you")
                                    wait(2)
                                    print("YOU LOSE")
                                    exit()
                                else:
                                    print("You slowly walk towards the guard...")
                                    wait(5)
                                    print("You are now behind the guard")
                                    wait(3)
                                    print("You stab the taser into his neck")
                                    wait(2)
                                    print("ZHzhzhzhz")
                                    wait(2)
                                    print("The guard shouts")
                                    wait(2)
                                    print("He turns around and shoots you")
                                    wait(2)
                                    print("YOU LOSE")
                                    exit()
                            else:
                                print("You realise that you don't have a taser")
                                wait(2)
                                print("You then grab your kunai instead")
                                wait(2)
                                print("Then suddenly the guard turns around")
                                wait(2)
                                print("He sees you")
                                wait(3)
                                print("YOU LOSE")
                                exit()
                    elif answer == 2:
                        if "stealth shoes" in items:
                            print("You are wearing your stealth shoes")
                            wait(2)
                            print("You see the door leading to the vault room")
                            wait(2)
                            print("You take a step")
                            wait(2)
                            print("The guard doesn't move")
                            wait(2)
                            print("You keep moving...")
                            wait(5)
                            print("eventually you reach the door")
                            wait(2)
                            print("you slowly turn the door knob")
                            wait(2)
                            print("There is a quiet click")
                            wait(2)
                            print("You look back at the guard")
                            wait(2)
                            print("He is still in the same position")
                            wait(2)
                            print("You walk into the room")
                            wait(2)
                            print("You close the door.")
                            wait(2)
                            print("You are in the vault room.")
                            inTheVault()
                        else:
                            print("You see the door leading to the vault room")
                            wait(2)
                            print("You take a step, it makes a noise")
                            wait(2)
                            print("The steps echoes around the room")
                            wait(2)
                            print("Suddenly you hear the guard shout")
                            wait(2)
                            print("PUT YOUR HANDS BEHIND YOUR HEAD!")
                            wait(3)
                            print("You get arrested")
                            exit()
        elif answer == 2:
            print("you decide to wait for a couple hours")
            wait(3)
            print("suddenly you hear a knock on your car window")
            wait(3)
            print("it's a guard...")
            wait(1)
            answer = choice(["act asleep and hide the weapons in the trunk", "kill him with your kunai", "surrender", "pretend there is no one in the car, the guard can't see through the black tinted windows so he does not know if someone is in there"])
            if answer == 1:
                print("you quickly shove your weapons and bags in the trunk")
                wait(0.6)
                answer = choice(["put your kunai in the trunk too", "keep it, just in case"])
                if answer == 2:
                    print("you shove toss your kunai into the trunk")
                    wait(0.7)
                    print("'Hello! anybody there?'")
                    wait(0.7)
                    print("you stay quiet...")
                    wait(0.5)
                    print("then you hear some muffled talking out side the window")
                    wait(0.6)
                    print("you hear a bunch of men running to the car..")
                    wait(0.2)
                    print("they start to shout")
                    wait(0.2)
                    print("'OPEN THE DOOR NOW!'")
                    wait(0.6)
                    answer = choice(["open the door", "keep it closed"])
                    if answer == 1:
                        print("you open the door...")
                        wait(0.4)
                        print("then grab you by the arms and arrest you")
                        wait(0.2)
                        print("The end")
                        exit()
                    elif answer == 2:
                        print("you decide to keep it closed and pretend to be asleep...")
                        wait(0.6)
                        print("they shoot the door handle")
                        wait(0.2)
                        print("the door opens")
                        wait(1)
                        print("you get arrested and put in jail for 4 years")
                        print("THE END")
                        exit()
                elif answer == 2:
                    wait(0.6)
                    answer = choice(["open the door", "keep it closed"])
                    if answer == 1:
                        print("you suddenly open the door, knocking the guard back")
                        wait(0.2)
                        print("you stab him in his heart with your kunai")
                        wait(0.1)
                        print("he stumbles to the ground, he does make a noise")
                        wait(0.5)
                        print("you push him under the car, then you walk to the bank")
                    elif answer == 2:
                        print("you get put in jail...")
                        wait(0.6)
                        print("THE END")
                        exit()
            elif answer == 2:
                print("you suddenly open the door, knocking the guard back")
                wait(4)
                print("you stab him in the heart with your kunai")
                wait(4)
                print("he stumbles to the ground, he makes no noise")
                wait(4)
                print("you push him under the car, then you walk to the bank")
            elif answer == 3:
                print("you open the door and put your hands behind your back")
                wait(0.6)
                print("The guards arrest you")
                exit()
            elif answer == 4:
                wait(0.6)
                answer = choice(["hide under the seat", "hide in the trunk"])
                if answer == 1:
                    print("you go under the seat")
                    wait(2)
                    answer = choice(["take your kunai just in case", f"take you {gun}"])
                    if answer == 1:
                        print("you grab your kunai and keep it in your pocket")
                    elif answer == 2:
                        if gun == "minigun":
                            print(f"you try to fit the {gun} under the seat but the tip of the sticks out a little")
                            wait(0.3)
                            print("eventually the guard gets a flashlight and brings it against the window")
                            wait(0.2)
                            print("he looks around a little...")
                            wait(1)
                            print(f"he then sees the tip of your {gun}")
                            wait(0.6)
                            print("YOU LOSE")
                            exit()
                        else:
                            print(f"you get you {gun} and hold it tight in your hand")
                elif answer == 2:
                    print("you quietly squeeze yourself into the trunk with all the other weapons")
                    wait(4)
                    print("'Hello!, is there anybody there!'")
                    print("the guard grabs a flash light and shines it into the window")
                    wait(4)
                    print("he puts his head against the window..")
                    wait(4)
                    print("he steps back from the car and shouts")
                    wait(4)
                    print("another guard shouts something back")
                    wait(8)
                    print("You are safe")
        print(f"it's 4am, you have your {gun}, all the guards are tired")
        wait(3)
        print("you are ready to rob the bank...")
        wait(2)
        print("You get out of your van")
        wait(2)
        if "stealth shoes" in items:
            print("Your footsteps make no noise.")
        else:
            print("With each step there is a small crunch, You slowly walk towards the fence")
            wait(3)
            print("Suddenly, A guard shouts")
            wait(1)
            answer = choice("", "", "")

def inTheVault(hasAfriend=False):
    #todo
    if hasAfriend:
        pass
    else:
        pass

def goesToJail():
    pass
